### PR TITLE
Add - Javascript The Right Way

### PR DESCRIPTION
**Pull request by weber97**
Nice guide to javascript. 

:)

### CODE REVIEW

**Comment by eugestarr** [comment]
double this one 👍

**Comment by bmorelli25** [comment]
This looks fantastic!

@weber97 - can you fix the merge conflicts and I'll merge the PR? Thanks

**Comment by weber97** [comment]
@bmorelli25 - It's done.

**Comment by bmorelli25** [comment]
moved it into the courses/tuts section.

**Pull request merged**
