### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robertmening01**
The links I've added are some incredibly useful resources that might be useful for those that come across this incredible list of resources... Let me know what you think :)

### CODE REVIEW

**Comment by robertmening01** [comment]
soooo?

**Comment by cpassolano** [comment]
I took a look and bookmarked those links, they are extremely useful.

**Comment by robertmening01** [comment]
I'm glad you liked them, hopefully Brandon will like them too and add them to the main list :)

**Comment by robertmening01** [comment]
I'm glad you liked them, hopefully Brandon will like them too and add them to the main list :)

**Comment by bmorelli25** [comment]
Thanks for the additions. Sorry for the delay

**Pull request merged**
