### PR TITLE
Updated HTML section

### PR DESCRIPTION
**Pull request by FlyingHouse47**
Added some links in HTML section:
- HTML & HTML5 basics
- HTML reference

Both points are linked to w3schools website.

### CODE REVIEW

**Comment by Roshanjossey** [comment]
@FlyingHouse47, I'm not sure if w3schools is a good resource to learn HTML.

We're having a conversation around this in #7 

Could you take a look in to that?

**Comment by FlyingHouse47** [comment]
@Roshanjossey Thank you for your reply. It is obviously that w3schools are not the greatest resource to learn HTML but in my opinion if you want to do some reseach for a specific tag or something, w3schools listed them all and describe it in more detail than e.g. SoloLearn what I have used.

**Comment by asantos3** [comment]
MDN has that too and is more reliable and complete:

[MDN HTML Reference.](https://developer.mozilla.org/en-US/docs/Web/Html/Reference)

**Comment by FlyingHouse47** [comment]
@asantos3 I think you are right guys - Don't let us fill the guide with unnecessary stuff of mine. 😆

**Comment by asantos3** [comment]
You could have put another commit and add the links on #7. Submit another pull request ;)

**Comment by bmorelli25** [comment]
@FlyingHouse47, Please feel free to submit a PR based on the recommendations made in #7 & #13. This is why we have discussion, so everyone can learn :)

**Pull request closed without merging**
