### PR TITLE
Add resouce to a hands on tutorial to make first pull request

### PR DESCRIPTION
**Pull request by Roshanjossey**
Add link to [first contributions](https://github.com/Roshanjossey/first-contributions)
which is a hands-on tutorial to get beginners to get started with contributing
to open source

### CODE REVIEW

**Comment by bmorelli25** [comment]
Good work on your repo! It looks very helpful. If you can fix the merge conflicts I'll get this added. Thanks

**Comment by Roshanjossey** [comment]
@bmorelli25: I'm on it.

**Comment by Roshanjossey** [comment]
@bmorelli25: Done

**Comment by bmorelli25** [comment]
Thanks! I want to keep the official guide at the top, so I moved your link to position two. Merging now!

**Pull request merged**
